using System.Collections.Generic;
using System.Linq;
using System.Text;
using TypeInfo = Json.Schema.Generation.SourceGeneration.TypeInfo;

namespace Json.Schema.Api.Analyzer;

/// <summary>
/// Emits the `GeneratedOpenApiFragment` class for one assembly.
/// </summary>
internal static class FragmentEmitter
{
	/// <summary>
	/// Emits the fragment source.
	/// </summary>
	/// <param name="types">The types with schemas.</param>
	/// <param name="endpoints">The discovered operations.</param>
	/// <param name="rootNamespace">The assembly's root namespace.</param>
	/// <returns>The generated source.</returns>
	public static string Emit(IReadOnlyList<TypeInfo> types, IReadOnlyList<EndpointInfo> endpoints, string rootNamespace)
	{
		var componentIds = ComponentSchemaEmitter.BuildComponentIds(types);

		var sb = new StringBuilder();
		sb.AppendLine("// <auto-generated/>");
		sb.AppendLine("#nullable enable");
		sb.AppendLine();
		sb.AppendLine("using Json.Schema;");
		sb.AppendLine("using Json.Schema.Api.OpenApi;");
		sb.AppendLine();

		if (!string.IsNullOrEmpty(rootNamespace))
		{
			sb.AppendLine($"namespace {rootNamespace};");
			sb.AppendLine();
		}

		sb.AppendLine("/// <summary>");
		sb.AppendLine("/// This assembly's contribution to an OpenAPI document.");
		sb.AppendLine("/// </summary>");
		sb.AppendLine($"public static class {OpenApiSourceGenerator.FragmentClassName}");
		sb.AppendLine("{");

		EmitSchemas(sb, types, componentIds);
		EmitFragment(sb, types, endpoints);

		sb.AppendLine("}");

		return sb.ToString();
	}

	private static void EmitSchemas(StringBuilder sb, IReadOnlyList<TypeInfo> types, Dictionary<string, string> componentIds)
	{
		foreach (var type in types.OrderBy(x => x.FullyQualifiedName))
		{
			var componentName = ComponentNaming.ForType(type.FullyQualifiedName);
			var expression = ComponentSchemaEmitter.EmitSchema(type, componentIds, "\t\t");

			sb.AppendLine($"\t/// <summary>The `{componentName}` component schema.</summary>");
			sb.AppendLine($"\tpublic static readonly JsonSchema {componentName} =");
			sb.AppendLine($"\t\t{expression}");
			sb.AppendLine("\t\t.Build();");
			sb.AppendLine();
		}
	}

	private static void EmitFragment(StringBuilder sb, IReadOnlyList<TypeInfo> types, IReadOnlyList<EndpointInfo> endpoints)
	{
		sb.AppendLine("\t/// <summary>");
		sb.AppendLine("\t/// Gets this assembly's fragment.");
		sb.AppendLine("\t/// </summary>");
		sb.AppendLine("\tpublic static readonly OpenApiFragment Fragment = new()");
		sb.AppendLine("\t{");

		EmitSchemaMap(sb, types);
		EmitComponentNameMap(sb, types);
		EmitOperations(sb, endpoints);

		sb.AppendLine("\t};");
	}

	private static void EmitSchemaMap(StringBuilder sb, IReadOnlyList<TypeInfo> types)
	{
		sb.AppendLine("\t\tSchemas = new global::System.Collections.Generic.Dictionary<string, JsonSchema>");
		sb.AppendLine("\t\t{");

		foreach (var type in types.OrderBy(x => x.FullyQualifiedName))
		{
			var componentName = ComponentNaming.ForType(type.FullyQualifiedName);
			sb.AppendLine($"\t\t\t[\"{componentName}\"] = {componentName},");
		}

		sb.AppendLine("\t\t},");
	}

	private static void EmitComponentNameMap(StringBuilder sb, IReadOnlyList<TypeInfo> types)
	{
		sb.AppendLine("\t\tComponentNames = new global::System.Collections.Generic.Dictionary<global::System.Type, string>");
		sb.AppendLine("\t\t{");

		foreach (var type in types.OrderBy(x => x.FullyQualifiedName))
		{
			var componentName = ComponentNaming.ForType(type.FullyQualifiedName);
			sb.AppendLine($"\t\t\t[typeof({type.FullyQualifiedName})] = \"{componentName}\",");
		}

		sb.AppendLine("\t\t},");
	}

	private static void EmitOperations(StringBuilder sb, IReadOnlyList<EndpointInfo> endpoints)
	{
		sb.AppendLine("\t\tOperations =");
		sb.AppendLine("\t\t[");

		foreach (var endpoint in endpoints.OrderBy(x => x.Route).ThenBy(x => x.Method))
		{
			sb.AppendLine("\t\t\tnew OpenApiFragmentOperation");
			sb.AppendLine("\t\t\t{");
			sb.AppendLine($"\t\t\t\tRoute = \"{Escape(endpoint.Route)}\",");
			sb.AppendLine($"\t\t\t\tMethod = \"{endpoint.Method}\",");

			if (endpoint.OperationId is not null)
				sb.AppendLine($"\t\t\t\tOperationId = \"{Escape(endpoint.OperationId)}\",");

			if (endpoint.RequestBodyTypeName is not null)
			{
				sb.AppendLine($"\t\t\t\tRequestBodyType = typeof({endpoint.RequestBodyTypeName}),");
				sb.AppendLine($"\t\t\t\tRequestBodyIsValidated = {(endpoint.RequestBodyIsValidated ? "true" : "false")},");
			}

			EmitParameters(sb, endpoint);
			EmitResponses(sb, endpoint);

			sb.AppendLine("\t\t\t},");
		}

		sb.AppendLine("\t\t],");
	}

	private static void EmitParameters(StringBuilder sb, EndpointInfo endpoint)
	{
		if (endpoint.Parameters.Count == 0) return;

		sb.AppendLine("\t\t\t\tParameters =");
		sb.AppendLine("\t\t\t\t[");

		foreach (var parameter in endpoint.Parameters)
		{
			sb.Append("\t\t\t\t\tnew OpenApiFragmentParameter { ");
			sb.Append($"Name = \"{Escape(parameter.Name)}\", ");
			sb.Append($"Location = \"{parameter.Location}\", ");
			sb.Append($"Required = {(parameter.Required ? "true" : "false")}");

			if (parameter.TypeName is not null)
				sb.Append($", Type = typeof({parameter.TypeName})");

			sb.AppendLine(" },");
		}

		sb.AppendLine("\t\t\t\t],");
	}

	private static void EmitResponses(StringBuilder sb, EndpointInfo endpoint)
	{
		if (endpoint.Responses.Count == 0) return;

		sb.AppendLine("\t\t\t\tResponses =");
		sb.AppendLine("\t\t\t\t[");

		foreach (var response in endpoint.Responses.OrderBy(x => x.StatusCode))
		{
			sb.Append("\t\t\t\t\tnew OpenApiFragmentResponse { ");
			sb.Append($"StatusCode = {response.StatusCode}, ");
			sb.Append($"Description = \"{Escape(response.Description)}\"");

			if (response.TypeName is not null)
				sb.Append($", Type = typeof({response.TypeName})");

			sb.AppendLine(" },");
		}

		sb.AppendLine("\t\t\t\t],");
	}

	private static string Escape(string value) =>
		value.Replace("\\", "\\\\").Replace("\"", "\\\"");
}
