using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using Json.Schema.Generation.SourceGeneration;
using TypeInfo = Json.Schema.Generation.SourceGeneration.TypeInfo;

namespace Json.Schema.Api.Analyzer;

/// <summary>
/// Emits the `GeneratedOpenApiFragment` class for one assembly.
/// </summary>
internal static class FragmentEmitter
{
	/// <summary>
	/// Emits the fragment source.
	/// </summary>
	/// <param name="types">The types with schemas.</param>
	/// <param name="endpoints">The discovered operations.</param>
	/// <param name="rootNamespace">The assembly's root namespace.</param>
	/// <param name="referencedFragments">The fragment classes of referenced assemblies.</param>
	/// <param name="enumFormat">The assembly's default enum format.</param>
	/// <returns>The generated source.</returns>
	public static string Emit(
		IReadOnlyList<TypeInfo> types,
		IReadOnlyList<EndpointInfo> endpoints,
		string rootNamespace,
		IReadOnlyList<string> referencedFragments,
		EnumFormat enumFormat)
	{
		var componentIds = ComponentSchemaEmitter.BuildComponentIds(types);

		var sb = new StringBuilder();
		sb.AppendLine("// <auto-generated/>");
		sb.AppendLine("#nullable enable");
		sb.AppendLine();
		sb.AppendLine("using System.Runtime.CompilerServices;");
		sb.AppendLine("using Json.Schema;");
		sb.AppendLine("using Json.Schema.Api.OpenApi;");
		sb.AppendLine();

		if (!string.IsNullOrEmpty(rootNamespace))
		{
			sb.AppendLine($"namespace {rootNamespace};");
			sb.AppendLine();
		}

		sb.AppendLine("/// <summary>");
		sb.AppendLine("/// This assembly's contribution to an OpenAPI document.");
		sb.AppendLine("/// </summary>");
		sb.AppendLine($"public static class {OpenApiSourceGenerator.FragmentClassName}");
		sb.AppendLine("{");

		// One fragment per description the assembly contributes to, so assembling a
		// description is a matter of collecting the fragments carrying its name rather than
		// filtering every operation in the application.  An endpoint named by several
		// descriptions appears in each; the schema fields below are shared, so only the map
		// entries repeat.
		var names = endpoints
			.SelectMany(x => x.DocumentNames.Count == 0 ? [null] : x.DocumentNames.Cast<string?>())
			.Distinct()
			.OrderBy(x => x, StringComparer.Ordinal)
			.ToArray();

		EmitSchemas(sb, types, componentIds);

		foreach (var name in names)
		{
			var selected = endpoints
				.Where(x => name is null ? x.DocumentNames.Count == 0 : x.DocumentNames.Contains(name))
				.ToArray();

			EmitFragment(sb, types, selected, name, FragmentFieldName(name), enumFormat);
		}

		EmitRegistration(sb, referencedFragments, names);

		sb.AppendLine("}");

		return sb.ToString();
	}

	private static void EmitRegistration(
		StringBuilder sb,
		IReadOnlyList<string> referencedFragments,
		IReadOnlyList<string?> names)
	{
		sb.AppendLine();
		sb.AppendLine("\t/// <summary>");
		sb.AppendLine("\t/// Ensures this assembly is loaded, so that its module initializer runs.");
		sb.AppendLine("\t/// </summary>");
		sb.AppendLine("\tpublic static void Register()");
		sb.AppendLine("\t{");
		sb.AppendLine("\t}");
		sb.AppendLine();
		sb.AppendLine("\t[ModuleInitializer]");
		sb.AppendLine("\tinternal static void Initialize()");
		sb.AppendLine("\t{");
		foreach (var name in names)
		{
			sb.AppendLine($"\t\tOpenApiFragmentRegistry.Add({FragmentFieldName(name)});");
		}

		if (referencedFragments.Count != 0)
		{
			sb.AppendLine();
			sb.AppendLine("\t\t// Touch each referenced assembly so that its module initializer runs too.");

			foreach (var fragment in referencedFragments)
			{
				sb.AppendLine($"\t\t{fragment}.Register();");
			}
		}

		sb.AppendLine("\t}");
	}

	private static void EmitSchemas(StringBuilder sb, IReadOnlyList<TypeInfo> types, Dictionary<string, string> componentIds)
	{
		foreach (var type in types.OrderBy(x => x.FullyQualifiedName))
		{
			var componentName = ComponentNaming.ForType(type.FullyQualifiedName);
			var expression = ComponentSchemaEmitter.EmitSchema(type, componentIds, "\t\t");

			sb.AppendLine($"\t/// <summary>The `{componentName}` component schema.</summary>");
			sb.AppendLine($"\tpublic static readonly JsonSchema {componentName} =");
			sb.AppendLine($"\t\t{expression}");
			sb.AppendLine("\t\t.Build();");
			sb.AppendLine();
		}
	}

	/// <summary>
	/// The field name holding the fragment for a description.
	/// </summary>
	private static string FragmentFieldName(string? name) =>
		name is null ? "Fragment" : $"Fragment_{Sanitize(name)}";

	/// <summary>
	/// Reduces a description name to an identifier, since it reaches the source as one.
	/// </summary>
	private static string Sanitize(string name)
	{
		var sb = new StringBuilder();

		foreach (var c in name)
		{
			sb.Append(char.IsLetterOrDigit(c) ? c : '_');
		}

		return sb.ToString();
	}

	private static void EmitFragment(
		StringBuilder sb,
		IReadOnlyList<TypeInfo> types,
		IReadOnlyList<EndpointInfo> endpoints,
		string? name,
		string fieldName,
		EnumFormat enumFormat)
	{
		sb.AppendLine();
		sb.AppendLine("\t/// <summary>");

		sb.AppendLine(name is null
			? "\t/// Gets this assembly's contribution to the default description."
			: $"\t/// Gets this assembly's contribution to the `{name}` description.");

		sb.AppendLine("\t/// </summary>");
		sb.AppendLine($"\tpublic static readonly OpenApiFragment {fieldName} = new()");
		sb.AppendLine("\t{");

		if (name is not null)
			sb.AppendLine($"\t\tName = \"{Escape(name)}\",");

		sb.AppendLine($"\t\tEnumFormat = global::Json.Schema.Generation.Serialization.EnumFormat.{enumFormat},");

		EmitSchemaMap(sb, types);
		EmitComponentNameMap(sb, types);
		EmitOperations(sb, endpoints);

		sb.AppendLine("\t};");
	}

	private static void EmitSchemaMap(StringBuilder sb, IReadOnlyList<TypeInfo> types)
	{
		sb.AppendLine("\t\tSchemas = new global::System.Collections.Generic.Dictionary<string, JsonSchema>");
		sb.AppendLine("\t\t{");

		foreach (var type in types.OrderBy(x => x.FullyQualifiedName))
		{
			var componentName = ComponentNaming.ForType(type.FullyQualifiedName);
			sb.AppendLine($"\t\t\t[\"{componentName}\"] = {componentName},");
		}

		sb.AppendLine("\t\t},");
	}

	private static void EmitComponentNameMap(StringBuilder sb, IReadOnlyList<TypeInfo> types)
	{
		sb.AppendLine("\t\tComponentNames = new global::System.Collections.Generic.Dictionary<global::System.Type, string>");
		sb.AppendLine("\t\t{");

		foreach (var type in types.OrderBy(x => x.FullyQualifiedName))
		{
			var componentName = ComponentNaming.ForType(type.FullyQualifiedName);
			sb.AppendLine($"\t\t\t[typeof({type.FullyQualifiedName})] = \"{componentName}\",");
		}

		sb.AppendLine("\t\t},");
	}

	private static void EmitOperations(StringBuilder sb, IReadOnlyList<EndpointInfo> endpoints)
	{
		sb.AppendLine("\t\tOperations =");
		sb.AppendLine("\t\t[");

		foreach (var endpoint in endpoints.OrderBy(x => x.Route).ThenBy(x => x.Method))
		{
			sb.AppendLine("\t\t\tnew OpenApiFragmentOperation");
			sb.AppendLine("\t\t\t{");
			// Normalized here rather than at discovery, since binding parameters needs the
			// constraints the template carries.
			var route = EndpointDiscoveryHelpers.NormalizeRoute(endpoint.Route);

			sb.AppendLine($"\t\t\t\tRoute = \"{Escape(route)}\",");
			sb.AppendLine($"\t\t\t\tMethod = \"{endpoint.Method}\",");


			if (endpoint.OperationId is not null)
				sb.AppendLine($"\t\t\t\tOperationId = \"{Escape(endpoint.OperationId)}\",");

			if (endpoint.Summary is not null)
				sb.AppendLine($"\t\t\t\tSummary = \"{Escape(endpoint.Summary)}\",");

			if (endpoint.Description is not null)
				sb.AppendLine($"\t\t\t\tDescription = \"{Escape(endpoint.Description)}\",");

			if (endpoint.Tags.Count != 0)
				sb.AppendLine($"\t\t\t\tTags = [{string.Join(", ", endpoint.Tags.Select(x => $"\"{Escape(x)}\""))}],");

			if (endpoint.RequestBodyTypeName is not null)
			{
				sb.AppendLine($"\t\t\t\tRequestBodyType = typeof({endpoint.RequestBodyTypeName}),");
				sb.AppendLine($"\t\t\t\tRequestBodyIsValidated = {(endpoint.RequestBodyIsValidated ? "true" : "false")},");

				if (endpoint.RequestBodyDescription is not null)
					sb.AppendLine($"\t\t\t\tRequestBodyDescription = \"{Escape(endpoint.RequestBodyDescription)}\",");
			}

			EmitParameters(sb, endpoint);
			EmitResponses(sb, endpoint);

			sb.AppendLine("\t\t\t},");
		}

		sb.AppendLine("\t\t],");
	}

	private static void EmitParameters(StringBuilder sb, EndpointInfo endpoint)
	{
		if (endpoint.Parameters.Count == 0) return;

		sb.AppendLine("\t\t\t\tParameters =");
		sb.AppendLine("\t\t\t\t[");

		foreach (var parameter in endpoint.Parameters)
		{
			sb.Append("\t\t\t\t\tnew OpenApiFragmentParameter { ");
			sb.Append($"Name = \"{Escape(parameter.Name)}\", ");
			sb.Append($"Location = \"{parameter.Location}\", ");
			sb.Append($"Required = {(parameter.Required ? "true" : "false")}");

			if (parameter.TypeName is not null)
				sb.Append($", Type = typeof({parameter.TypeName})");

			if (parameter.Description is not null)
				sb.Append($", Description = \"{Escape(parameter.Description)}\"");

			sb.AppendLine(" },");
		}

		sb.AppendLine("\t\t\t\t],");
	}

	private static void EmitResponses(StringBuilder sb, EndpointInfo endpoint)
	{
		if (endpoint.Responses.Count == 0) return;

		sb.AppendLine("\t\t\t\tResponses =");
		sb.AppendLine("\t\t\t\t[");

		foreach (var response in endpoint.Responses.OrderBy(x => x.StatusCode))
		{
			sb.Append("\t\t\t\t\tnew OpenApiFragmentResponse { ");
			sb.Append($"StatusCode = {response.StatusCode}, ");
			sb.Append($"Description = \"{Escape(response.Description)}\"");

			if (response.TypeName is not null)
				sb.Append($", Type = typeof({response.TypeName})");

			sb.AppendLine(" },");
		}

		sb.AppendLine("\t\t\t\t],");
	}

	private static string Escape(string value) =>
		value.Replace("\\", "\\\\").Replace("\"", "\\\"").Replace("\r", string.Empty).Replace("\n", "\\n");
}
