using Json.Schema.Keywords;

namespace Json.Schema;

public partial class SchemaKeywordRegistry
{
	public static SchemaKeywordRegistry Draft06 { get; } = new(
		new Keywords.Draft06.AdditionalItemsKeyword(),
		new AdditionalPropertiesKeyword(),
		new AllOfKeyword(),
		new AnyOfKeyword(),
		new CommentKeyword(),
		new ConstKeyword(),
		new Keywords.Draft06.ContainsKeyword(),
		new DefaultKeyword(),
		new Keywords.Draft06.DefinitionsKeyword(),
		new DependenciesKeyword(),
		new DescriptionKeyword(),
		//new ElseKeyword(),
		new EnumKeyword(),
		new ExamplesKeyword(),
		new ExclusiveMaximumKeyword(),
		new ExclusiveMinimumKeyword(),
		new Keywords.Draft06.FormatKeyword(),
		new Keywords.Draft06.IdKeyword(),
		//new IfKeyword(),
		new Keywords.Draft06.ItemsKeyword(),
		new MaximumKeyword(),
		new MaxItemsKeyword(),
		new MaxLengthKeyword(),
		new MaxPropertiesKeyword(),
		new MinimumKeyword(),
		new MinItemsKeyword(),
		new MinLengthKeyword(),
		new MinPropertiesKeyword(),
		new MultipleOfKeyword(),
		new NotKeyword(),
		new OneOfKeyword(),
		new PatternKeyword(),
		new PatternPropertiesKeyword(),
		new PropertiesKeyword(),
		//new PropertyDependenciesKeyword(),
		new PropertyNamesKeyword(),
		new RefKeyword(),
		new RequiredKeyword(),
		new SchemaKeyword(),
		//new ThenKeyword(),
		new TitleKeyword(),
		new TypeKeyword()
		//new UnevaluatedItemsKeyword(),
		//new UnevaluatedPropertiesKeyword(),
		//new UniqueItemsKeyword(),
		//new VocabularyKeyword(),
	);
}