using Json.Schema.Keywords;
using Json.Schema.Keywords.Draft201909;

namespace Json.Schema;

public partial class SchemaKeywordRegistry
{
	public static SchemaKeywordRegistry Draft201909 { get; } = new(
		//new AdditionalItemsKeyword(),
		//new AdditionalPropertiesKeyword(),
		//new AllOfKeyword(),
		new Keywords.Draft201909.AnchorKeyword(),
		//new AnyOfKeyword(),
		//new CommentKeyword(),
		//new ConstKeyword(),
		//new ContainsKeyword(),
		//new ContentEncodingKeyword(),
		//new ContentMediaTypeKeyword(),
		//new ContentSchemaKeyword(),
		//new DefaultKeyword(),
		//new DefinitionsKeyword(),
		new DefsKeyword(),
		//new DependenciesKeyword(),
		//new DependentRequiredKeyword(),
		//new DependentSchemasKeyword(),
		//new DeprecatedKeyword(),
		//new DescriptionKeyword(),
		//new ElseKeyword(),
		//new EnumKeyword(),
		//new ExamplesKeyword(),
		//new ExclusiveMaximumKeyword(),
		//new ExclusiveMinimumKeyword(),
		//new FormatKeyword(),
		new IdKeyword(),
		//new IfKeyword(),
		new ItemsKeyword(),
		//new MaxContainsKeyword(),
		//new MaximumKeyword(),
		//new MaxItemsKeyword(),
		//new MaxLengthKeyword(),
		//new MaxPropertiesKeyword(),
		//new MinContainsKeyword(),
		//new MinimumKeyword(),
		//new MinItemsKeyword(),
		//new MinLengthKeyword(),
		//new MinPropertiesKeyword(),
		//new MultipleOfKeyword(),
		//new NotKeyword(),
		//new OneOfKeyword(),
		//new PatternKeyword(),
		//new PatternPropertiesKeyword(),
		//new PrefixItemsKeyword(),
		new PropertiesKeyword(),
		//new PropertyDependenciesKeyword(),
		//new PropertyNamesKeyword(),
		//new ReadOnlyKeyword(),
		new RecursiveAnchorKeyword(),
		new RecursiveRefKeyword(),
		new RefKeyword(),
		//new RequiredKeyword(),
		//new SchemaKeyword(),
		//new ThenKeyword(),
		//new TitleKeyword(),
		new TypeKeyword()
		//new UnevaluatedItemsKeyword(),
		//new UnevaluatedPropertiesKeyword(),
		//new UniqueItemsKeyword(),
		//new VocabularyKeyword(),
		//new WriteOnlyKeyword(),
	);
}