using Json.Schema.Keywords;

namespace Json.Schema;

public partial class SchemaKeywordRegistry
{
	public static SchemaKeywordRegistry Draft201909 { get; } = new(
		new Keywords.Draft06.AdditionalItemsKeyword(),
		new AdditionalPropertiesKeyword(),
		new AllOfKeyword(),
		new Keywords.Draft201909.AnchorKeyword(),
		new AnyOfKeyword(),
		new CommentKeyword(),
		new ConstKeyword(),
		new ContainsKeyword(),
		new ContentEncodingKeyword(),
		new ContentMediaTypeKeyword(),
		new ContentSchemaKeyword(),
		new DefaultKeyword(),
		new DefsKeyword(),
		new DependentRequiredKeyword(),
		new DependentSchemasKeyword(),
		new DeprecatedKeyword(),
		new DescriptionKeyword(),
		//new ElseKeyword(),
		new EnumKeyword(),
		new ExamplesKeyword(),
		new ExclusiveMaximumKeyword(),
		new ExclusiveMinimumKeyword(),
		new Keywords.Draft06.FormatKeyword(),
		new IdKeyword(),
		//new IfKeyword(),
		new Keywords.Draft06.ItemsKeyword(),
		new MaxContainsKeyword(),
		new MaximumKeyword(),
		new MaxItemsKeyword(),
		new MaxLengthKeyword(),
		new MaxPropertiesKeyword(),
		new MinContainsKeyword(),
		new MinimumKeyword(),
		new MinItemsKeyword(),
		new MinLengthKeyword(),
		new MinPropertiesKeyword(),
		new MultipleOfKeyword(),
		new NotKeyword(),
		new OneOfKeyword(),
		new PatternKeyword(),
		new PatternPropertiesKeyword(),
		new PropertiesKeyword(),
		//new PropertyDependenciesKeyword(),
		new PropertyNamesKeyword(),
		new ReadOnlyKeyword(),
		new Keywords.Draft201909.RecursiveAnchorKeyword(),
		new Keywords.Draft201909.RecursiveRefKeyword(),
		new RefKeyword(),
		new RequiredKeyword(),
		new SchemaKeyword(),
		//new ThenKeyword(),
		new TitleKeyword(),
		new TypeKeyword(),
		//new UnevaluatedItemsKeyword(),
		//new UnevaluatedPropertiesKeyword(),
		new UniqueItemsKeyword(),
		//new VocabularyKeyword(),
		new WriteOnlyKeyword()
	);
}