using Json.Schema.Keywords;

namespace Json.Schema;

public partial class SchemaKeywordRegistry
{
	public static SchemaKeywordRegistry V1 { get; } = new(
		new AdditionalPropertiesKeyword(),
		new AllOfKeyword(),
		new AnchorKeyword(),
		new AnyOfKeyword(),
		new CommentKeyword(),
		new ConstKeyword(),
		new ContainsKeyword(),
		new ContentEncodingKeyword(),
		new ContentMediaTypeKeyword(),
		new ContentSchemaKeyword(),
		new DefaultKeyword(),
		new DefsKeyword(),
		new DependentRequiredKeyword(),
		new DependentSchemasKeyword(),
		new DeprecatedKeyword(),
		new DescriptionKeyword(),
		new DynamicAnchorKeyword(),
		new DynamicRefKeyword(),
		//new ElseKeyword(),
		new EnumKeyword(),
		new ExamplesKeyword(),
		new ExclusiveMaximumKeyword(),
		new ExclusiveMinimumKeyword(),
		new FormatKeyword(),
		new IdKeyword(),
		//new IfKeyword(),
		new ItemsKeyword(),
		new MaxContainsKeyword(),
		new MaximumKeyword(),
		new MaxItemsKeyword(),
		new MaxLengthKeyword(),
		new MaxPropertiesKeyword(),
		new MinContainsKeyword(),
		new MinimumKeyword(),
		new MinItemsKeyword(),
		new MinLengthKeyword(),
		new MinPropertiesKeyword(),
		new MultipleOfKeyword(),
		new NotKeyword(),
		new OneOfKeyword(),
		new PatternKeyword(),
		new PatternPropertiesKeyword(),
		new PrefixItemsKeyword(),
		new PropertiesKeyword(),
		//new PropertyDependenciesKeyword(),
		new PropertyNamesKeyword(),
		new ReadOnlyKeyword(),
		new RefKeyword(),
		new RequiredKeyword(),
		new SchemaKeyword(),
		//new ThenKeyword(),
		new TitleKeyword(),
		new TypeKeyword(),
		//new UnevaluatedItemsKeyword(),
		//new UnevaluatedPropertiesKeyword(),
		//new UniqueItemsKeyword(),
		//new VocabularyKeyword(),
		new WriteOnlyKeyword()
	);
}