using System.Collections.Generic;
using System.Collections.Immutable;
using System.Text;
using System.Threading;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;
using Microsoft.CodeAnalysis.CSharp.Syntax;

namespace Json.MergePatch;

[Generator]
public sealed class MergePatchGenerator : IIncrementalGenerator
{
	private const string AttributeFullName = "Json.MergePatch.GenerateMergePatchUpdateAttribute";

	private const string AttributeSource = """
		// <auto-generated/>
		#nullable enable
		namespace Json.MergePatch;

		/// <summary>
		/// Marks a class for compile-time JSON Merge Patch (RFC 7396) source generation.
		/// The class must be declared <c>partial</c>.
		/// </summary>
		[global::System.AttributeUsage(global::System.AttributeTargets.Class, AllowMultiple = false, Inherited = false)]
		public sealed class GenerateMergePatchUpdateAttribute : global::System.Attribute { }
		""";

	public void Initialize(IncrementalGeneratorInitializationContext context)
	{
		context.RegisterPostInitializationOutput(ctx =>
			ctx.AddSource("GenerateMergePatchUpdateAttribute.g.cs", AttributeSource));

		var provider = context.SyntaxProvider
			.ForAttributeWithMetadataName(
				AttributeFullName,
				(node, _) => node is ClassDeclarationSyntax,
				GetClassModel)
			.Where(m => m is not null);

		context.RegisterSourceOutput(provider, (ctx, model) =>
		{
			if (model is null) return;
			ctx.AddSource($"{model!.FullName.Replace('.', '_').Replace('<', '_').Replace('>', '_')}.UpdateDto.g.cs",
				GenerateSource(model));
		});
	}

	private static ClassModel? GetClassModel(GeneratorAttributeSyntaxContext ctx, CancellationToken ct)
	{
		if (ctx.TargetSymbol is not INamedTypeSymbol classSymbol) return null;

		if (ctx.TargetNode is not ClassDeclarationSyntax cds) return null;

		var isPartial = false;
		foreach (var mod in cds.Modifiers)
		{
			if (mod.IsKind(SyntaxKind.PartialKeyword))
			{
				isPartial = true;
				break;
			}
		}

		if (!isPartial) return null;

		var ns = classSymbol.ContainingNamespace.IsGlobalNamespace
			? null
			: classSymbol.ContainingNamespace.ToDisplayString();

		var className = classSymbol.Name;
		var fullName = classSymbol.ToDisplayString();

		var properties = new List<PropertyModel>();
		foreach (var member in classSymbol.GetMembers())
		{
			ct.ThrowIfCancellationRequested();

			if (member is not IPropertySymbol prop) continue;
			if (prop.DeclaredAccessibility != Accessibility.Public) continue;
			if (prop.IsStatic) continue;
			if (prop.IsIndexer) continue;
			if (prop.GetMethod is null || prop.SetMethod is null) continue;

			var jsonName = GetJsonPropertyName(prop);
			var model = GetPropertyModel(prop, jsonName);
			properties.Add(model);
		}

		return new ClassModel(ns, className, fullName, properties.ToImmutableArray());
	}

	private static string GetJsonPropertyName(IPropertySymbol prop)
	{
		foreach (var attr in prop.GetAttributes())
		{
			if (attr.AttributeClass?.ToDisplayString() == "System.Text.Json.Serialization.JsonPropertyNameAttribute" &&
			    attr.ConstructorArguments.Length > 0 &&
			    attr.ConstructorArguments[0].Value is string name)
				return name;
		}

		return prop.Name;
	}

	private static PropertyModel GetPropertyModel(IPropertySymbol prop, string jsonName)
	{
		var type = prop.Type;

		// Check for Nullable<T> (value type nullable, e.g. int?)
		ITypeSymbol underlyingType = type;
		var isNullableValueType = false;
		if (type is INamedTypeSymbol { IsGenericType: true } namedType &&
		    namedType.OriginalDefinition.SpecialType == SpecialType.System_Nullable_T)
		{
			underlyingType = namedType.TypeArguments[0];
			isNullableValueType = true;
		}

		// Check for nullable reference type (e.g. string?, MyClass?)
		var isNullableRef = type.IsReferenceType && type.NullableAnnotation == NullableAnnotation.Annotated;
		var isNullable = isNullableValueType || isNullableRef;

		// Check if underlying type has [GenerateMergePatchUpdate]
		var isUpdateDto = false;
		foreach (var attr in underlyingType.GetAttributes())
		{
			if (attr.AttributeClass?.ToDisplayString() == AttributeFullName)
			{
				isUpdateDto = true;
				break;
			}
		}

		// Fully-qualified base type name (no nullability annotation)
		var baseTypeFq = underlyingType
			.WithNullableAnnotation(NullableAnnotation.None)
			.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat);

		string innerTypeName;
		string? concreteTypeName = null;

		if (isUpdateDto)
		{
			concreteTypeName = baseTypeFq;
			innerTypeName = isNullable ? $"{baseTypeFq}.UpdateDto?" : $"{baseTypeFq}.UpdateDto";
		}
		else if (isNullableValueType)
		{
			innerTypeName = $"{baseTypeFq}?";
		}
		else if (isNullableRef)
		{
			innerTypeName = $"{baseTypeFq}?";
		}
		else
		{
			innerTypeName = baseTypeFq;
		}

		return new PropertyModel(prop.Name, jsonName, innerTypeName, isUpdateDto, isNullable, concreteTypeName);
	}

	private static string GenerateSource(ClassModel model)
	{
		var sb = new StringBuilder();
		sb.AppendLine("// <auto-generated/>");
		sb.AppendLine("#nullable enable");
		sb.AppendLine();

		if (model.Namespace is not null)
		{
			sb.AppendLine($"namespace {model.Namespace};");
			sb.AppendLine();
		}

		sb.AppendLine($"public partial class {model.ClassName}");
		sb.AppendLine("{");
		sb.AppendLine("\tpublic sealed class UpdateDto");
		sb.AppendLine("\t{");

		// Properties
		foreach (var prop in model.Properties)
		{
			if (prop.JsonName != prop.CSharpName)
				sb.AppendLine($"\t\t[global::System.Text.Json.Serialization.JsonPropertyName(\"{EscapeString(prop.JsonName)}\")]");
			sb.AppendLine($"\t\tpublic global::DotNext.Optional<{prop.InnerTypeName}> {prop.CSharpName} {{ get; init; }}");
		}

		sb.AppendLine();

			   // ...existing code...

		// ApplyTo
		sb.AppendLine($"\t\tpublic void ApplyTo({model.ClassName} target)");
		sb.AppendLine("\t\t{");

		foreach (var prop in model.Properties)
		{
			if (prop.IsUpdateDto)
			{
				sb.AppendLine($"\t\t\tif (!{prop.CSharpName}.IsUndefined)");
				sb.AppendLine("\t\t\t{");

				if (prop.IsNullable)
				{
					sb.AppendLine($"\t\t\t\tif ({prop.CSharpName}.IsNull)");
					sb.AppendLine($"\t\t\t\t\ttarget.{prop.CSharpName} = null;");
					sb.AppendLine("\t\t\t\telse");
					sb.AppendLine("\t\t\t\t{");
					sb.AppendLine($"\t\t\t\t\ttarget.{prop.CSharpName} ??= new {prop.ConcreteTypeName}();");
					sb.AppendLine($"\t\t\t\t\t{prop.CSharpName}.Value!.ApplyTo(target.{prop.CSharpName});");
					sb.AppendLine("\t\t\t\t}");
				}
				else
				{
					sb.AppendLine($"\t\t\t\ttarget.{prop.CSharpName} ??= new {prop.ConcreteTypeName}();");
					sb.AppendLine($"\t\t\t\t{prop.CSharpName}.Value.ApplyTo(target.{prop.CSharpName});");
				}

				sb.AppendLine("\t\t\t}");
			}
			else
			{
				sb.AppendLine($"\t\t\tif (!{prop.CSharpName}.IsUndefined)");
				sb.AppendLine("\t\t\t{");
				if (prop.IsNullable)
				{
					sb.AppendLine($"\t\t\t\tif ({prop.CSharpName}.IsNull)");
					sb.AppendLine($"\t\t\t\t\ttarget.{prop.CSharpName} = null;");
					sb.AppendLine("\t\t\t\telse");
					sb.AppendLine($"\t\t\t\t\ttarget.{prop.CSharpName} = {prop.CSharpName}.Value;");
				}
				else
				{
					sb.AppendLine($"\t\t\t\ttarget.{prop.CSharpName} = {prop.CSharpName}.Value;");
				}
				sb.AppendLine("\t\t\t}");
			}
		}

		sb.AppendLine("\t\t}");
		sb.AppendLine("\t}");
		sb.AppendLine("}");

		return sb.ToString();
	}

	private static string EscapeString(string value) =>
		value.Replace("\\", "\\\\").Replace("\"", "\\\"");

	private static string VarName(string name) =>
		char.ToLowerInvariant(name[0]) + name.Substring(1);
}

internal sealed record ClassModel(
	string? Namespace,
	string ClassName,
	string FullName,
	ImmutableArray<PropertyModel> Properties);

internal sealed record PropertyModel(
	string CSharpName,
	string JsonName,
	string InnerTypeName,
	bool IsUpdateDto,
	bool IsNullable,
	string? ConcreteTypeName);
