using System.Collections.Generic;
using System.Collections.Immutable;
using System.Linq;
using System.Text;
using System.Threading;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;
using Microsoft.CodeAnalysis.CSharp.Syntax;

namespace Json.MergePatch;

[Generator]
public sealed class MergePatchGenerator : IIncrementalGenerator
{
	private const string _attributeFullName = "Json.MergePatch.GenerateMergePatchUpdateAttribute";
	private const string _patchIgnoreAttributeFullName = "Json.MergePatch.PatchIgnoreAttribute";
	private const string _nestingModeFullName = "Json.MergePatch.NestingMode";
	private const string _defaultPatchTypeName = "PatchModel";

	private const string _attributeSource = """
	// <auto-generated/>
	#nullable enable
	namespace Json.MergePatch;

	public enum NestingMode
	{
		Automatic = 0,
		Subclass = 1,
		SameNamespace = 2
	}

	/// <summary>
	/// Marks a class for compile-time JSON Merge Patch (RFC 7396) source generation.
	/// The class must be declared <c>partial</c> if patch type is nested.
	/// </summary>
	[global::System.AttributeUsage(global::System.AttributeTargets.Class, AllowMultiple = false, Inherited = false)]
	public sealed class GenerateMergePatchUpdateAttribute : global::System.Attribute
	{
		public string Name { get; set; } = "PatchModel";
		public NestingMode Nesting { get; set; } = NestingMode.Automatic;
	}

	/// <summary>
	/// Excludes a property from generated merge patch models.
	/// Useful for fields like identifiers that should be part of the route, not request payload.
	/// </summary>
	[global::System.AttributeUsage(global::System.AttributeTargets.Property, AllowMultiple = false, Inherited = true)]
	public sealed class PatchIgnoreAttribute : global::System.Attribute;
	""";

	public void Initialize(IncrementalGeneratorInitializationContext context)
	{
		context.RegisterPostInitializationOutput(ctx =>
			ctx.AddSource("GenerateMergePatchUpdateAttribute.g.cs", _attributeSource));

		var provider = context.SyntaxProvider
			.ForAttributeWithMetadataName(
				_attributeFullName,
				(node, _) => node is ClassDeclarationSyntax,
				GetClassModel)
			.Where(m => m is not null);

		context.RegisterSourceOutput(provider, (ctx, model) =>
		{
			if (model is null) return;
			ctx.AddSource($"{model!.FullName.Replace('.', '_').Replace('<', '_').Replace('>', '_')}.{model.PatchTypeName}.g.cs",
				GenerateSource(model));
		});
	}

	private static ClassModel? GetClassModel(GeneratorAttributeSyntaxContext ctx, CancellationToken ct)
	{
		if (ctx.TargetSymbol is not INamedTypeSymbol classSymbol) return null;

		if (ctx.TargetNode is not ClassDeclarationSyntax cds) return null;

		var isPartial = cds.Modifiers.Any(mod => mod.IsKind(SyntaxKind.PartialKeyword));
		var nestingMode = GetNestingMode(classSymbol);
		var generateAsNested = nestingMode switch
		{
			NestingMode.Subclass => isPartial,
			NestingMode.SameNamespace => false,
			_ => isPartial
		};

		var ns = classSymbol.ContainingNamespace.IsGlobalNamespace
			? null
			: classSymbol.ContainingNamespace.ToDisplayString();

		var className = classSymbol.Name;
		var fullName = classSymbol.ToDisplayString();
		var patchTypeName = GetPatchTypeName(classSymbol);
		var emittedPatchTypeName = generateAsNested
			? patchTypeName
			: $"{className}{patchTypeName}";

		var properties = new List<PropertyModel>();
		foreach (var member in classSymbol.GetMembers())
		{
			ct.ThrowIfCancellationRequested();

			if (member is not IPropertySymbol prop) continue;
			if (prop.DeclaredAccessibility != Accessibility.Public) continue;
			if (prop.IsStatic) continue;
			if (prop.IsIndexer) continue;
			if (prop.GetMethod is null || prop.SetMethod is null) continue;
			if (IsPatchIgnored(prop)) continue;

			var jsonName = TryGetJsonPropertyName(prop);
			var model = GetPropertyModel(prop, jsonName);
			properties.Add(model);
		}

		return new ClassModel(ns, className, fullName, patchTypeName, emittedPatchTypeName, generateAsNested, properties.ToImmutableArray());
	}

	private static bool IsPatchIgnored(IPropertySymbol prop)
	{
		foreach (var attr in prop.GetAttributes())
		{
			if (attr.AttributeClass?.ToDisplayString() == _patchIgnoreAttributeFullName)
				return true;
		}

		return false;
	}

	private static string? TryGetJsonPropertyName(IPropertySymbol prop)
	{
		foreach (var attr in prop.GetAttributes())
		{
			if (attr.AttributeClass?.ToDisplayString() == "System.Text.Json.Serialization.JsonPropertyNameAttribute" &&
			    attr.ConstructorArguments.Length > 0 &&
			    attr.ConstructorArguments[0].Value is string name)
				return name;
		}

		return null;
	}

	private static string GetPatchTypeName(ITypeSymbol type)
	{
		foreach (var attr in type.GetAttributes())
		{
			if (attr.AttributeClass?.ToDisplayString() != _attributeFullName) continue;

			foreach (var namedArg in attr.NamedArguments)
			{
				if (namedArg.Key == "Name" &&
				    namedArg.Value.Value is string namedValue &&
				    !string.IsNullOrWhiteSpace(namedValue))
					return namedValue;
			}

			if (attr.ConstructorArguments.Length > 0 &&
			    attr.ConstructorArguments[0].Value is string configuredName &&
			    !string.IsNullOrWhiteSpace(configuredName))
				return configuredName;

			return _defaultPatchTypeName;
		}

		return _defaultPatchTypeName;
	}

	private static NestingMode GetNestingMode(ITypeSymbol type)
	{
		foreach (var attr in type.GetAttributes())
		{
			if (attr.AttributeClass?.ToDisplayString() != _attributeFullName) continue;

			foreach (var namedArg in attr.NamedArguments)
			{
				if (namedArg.Key == "Nesting" &&
				    namedArg.Value.Type?.ToDisplayString() == _nestingModeFullName &&
				    namedArg.Value.Value is int value)
					return (NestingMode)value;
			}

			if (attr.ConstructorArguments.Length > 1 &&
			    attr.ConstructorArguments[1].Value is int configuredValue)
				return (NestingMode)configuredValue;

			return NestingMode.Automatic;
		}

		return NestingMode.Automatic;
	}

	private static PropertyModel GetPropertyModel(IPropertySymbol prop, string? jsonName)
	{
		var type = prop.Type;

		// Check for Nullable<T> (value type nullable, e.g. int?)
		var underlyingType = type;
		var isNullableValueType = false;
		if (type is INamedTypeSymbol { IsGenericType: true } namedType &&
		    namedType.OriginalDefinition.SpecialType == SpecialType.System_Nullable_T)
		{
			underlyingType = namedType.TypeArguments[0];
			isNullableValueType = true;
		}

		// Check for nullable reference type (e.g. string?, MyClass?)
		var isNullableRef = type.IsReferenceType && type.NullableAnnotation == NullableAnnotation.Annotated;
		var isNullable = isNullableValueType || isNullableRef;

		// Check if underlying type has [GenerateMergePatchUpdate]
		var isPatchModel = false;
		var nestedPatchTypeFq = string.Empty;
		foreach (var attr in underlyingType.GetAttributes())
		{
			if (attr.AttributeClass?.ToDisplayString() == _attributeFullName)
			{
				isPatchModel = true;
				var nestedPatchTypeName = GetPatchTypeName(underlyingType);
				nestedPatchTypeFq = GetPatchTypeReference(underlyingType, nestedPatchTypeName);
				break;
			}
		}

		// Fully-qualified base type name (no nullability annotation)
		var baseTypeFq = underlyingType
			.WithNullableAnnotation(NullableAnnotation.None)
			.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat);

		string innerTypeName;
		string? concreteTypeName = null;

		if (isPatchModel)
		{
			concreteTypeName = baseTypeFq;
			innerTypeName = isNullable ? $"{nestedPatchTypeFq}?" : nestedPatchTypeFq;
		}
		else if (isNullableValueType || isNullableRef)
			innerTypeName = $"{baseTypeFq}?";
		else
			innerTypeName = baseTypeFq;

		return new PropertyModel(prop.Name, jsonName, innerTypeName, isPatchModel, isNullable, concreteTypeName);
	}

	private static string GetPatchTypeReference(ITypeSymbol type, string patchTypeName)
	{
		var mode = GetNestingMode(type);
		var typeName = type.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat)
			.WithoutNullableSuffix();

		var canNest = mode switch
		{
			NestingMode.SameNamespace => false,
			_ => IsPartial(type)
		};

		return canNest ? $"{typeName}.{patchTypeName}" : $"{typeName}{patchTypeName}";
	}

	private static bool IsPartial(ITypeSymbol type)
	{
		if (type is not INamedTypeSymbol namedType) return false;

		foreach (var syntaxRef in namedType.DeclaringSyntaxReferences)
		{
			if (syntaxRef.GetSyntax() is TypeDeclarationSyntax declaration &&
			    declaration.Modifiers.Any(m => m.IsKind(SyntaxKind.PartialKeyword)))
				return true;
		}

		return false;
	}

	private static string GenerateSource(ClassModel model)
	{
		var sb = new StringBuilder();
		sb.AppendLine("// <auto-generated/>");
		sb.AppendLine("#nullable enable");
		sb.AppendLine();

		if (model.Namespace is not null)
		{
			sb.AppendLine($"namespace {model.Namespace};");
			sb.AppendLine();
		}

		if (model.GenerateAsNested)
		{
			sb.AppendLine($"public partial class {model.ClassName}");
			sb.AppendLine("{");
			sb.AppendLine($"\tpublic sealed class {model.EmittedPatchTypeName}");
			sb.AppendLine("\t{");
		}
		else
		{
			sb.AppendLine($"public sealed class {model.EmittedPatchTypeName}");
			sb.AppendLine("{");
		}

		// Properties
		foreach (var prop in model.Properties)
		{
			if (prop.JsonName is not null)
				sb.AppendLine(model.GenerateAsNested
					? $"\t\t[global::System.Text.Json.Serialization.JsonPropertyName(\"{EscapeString(prop.JsonName)}\")]"
					: $"\t[global::System.Text.Json.Serialization.JsonPropertyName(\"{EscapeString(prop.JsonName)}\")]");
			sb.AppendLine(model.GenerateAsNested
				? $"\t\tpublic global::DotNext.Optional<{prop.InnerTypeName}> {prop.CSharpName} {{ get; init; }}"
				: $"\tpublic global::DotNext.Optional<{prop.InnerTypeName}> {prop.CSharpName} {{ get; init; }}");
		}

		sb.AppendLine();


		// ApplyTo
		sb.AppendLine(model.GenerateAsNested
			? $"\t\tpublic void ApplyTo({model.ClassName} target)"
			: $"\tpublic void ApplyTo({model.ClassName} target)");
		sb.AppendLine(model.GenerateAsNested ? "\t\t{" : "\t{");

		foreach (var prop in model.Properties)
		{
			if (prop.IsPatchModel)
			{
				sb.AppendLine(model.GenerateAsNested
					? $"\t\t\tif (!{prop.CSharpName}.IsUndefined)"
					: $"\t\tif (!{prop.CSharpName}.IsUndefined)");
				sb.AppendLine(model.GenerateAsNested ? "\t\t\t{" : "\t\t{");

				if (prop.IsNullable)
				{
					sb.AppendLine(model.GenerateAsNested ? $"\t\t\t\tif ({prop.CSharpName}.IsNull)" : $"\t\t\tif ({prop.CSharpName}.IsNull)");
					sb.AppendLine(model.GenerateAsNested ? $"\t\t\t\t\ttarget.{prop.CSharpName} = null;" : $"\t\t\t\ttarget.{prop.CSharpName} = null;");
					sb.AppendLine(model.GenerateAsNested ? "\t\t\t\telse" : "\t\t\telse");
					sb.AppendLine(model.GenerateAsNested ? "\t\t\t\t{" : "\t\t\t{");
					sb.AppendLine(model.GenerateAsNested ? $"\t\t\t\t\ttarget.{prop.CSharpName} ??= new {prop.ConcreteTypeName}();" : $"\t\t\t\ttarget.{prop.CSharpName} ??= new {prop.ConcreteTypeName}();");
					sb.AppendLine(model.GenerateAsNested ? $"\t\t\t\t\t{prop.CSharpName}.Value!.ApplyTo(target.{prop.CSharpName});" : $"\t\t\t\t{prop.CSharpName}.Value!.ApplyTo(target.{prop.CSharpName});");
					sb.AppendLine(model.GenerateAsNested ? "\t\t\t\t}" : "\t\t\t}");
				}
				else
				{
					sb.AppendLine($"\t\t\t\ttarget.{prop.CSharpName} ??= new {prop.ConcreteTypeName}();");
					sb.AppendLine($"\t\t\t\t{prop.CSharpName}.Value.ApplyTo(target.{prop.CSharpName});");
				}

				sb.AppendLine(model.GenerateAsNested ? "\t\t\t}" : "\t\t}");
			}
			else
			{
				sb.AppendLine(model.GenerateAsNested ? $"\t\t\tif (!{prop.CSharpName}.IsUndefined)" : $"\t\tif (!{prop.CSharpName}.IsUndefined)");
				sb.AppendLine(model.GenerateAsNested ? "\t\t\t{" : "\t\t{");
				if (prop.IsNullable)
				{
					sb.AppendLine(model.GenerateAsNested ? $"\t\t\t\tif ({prop.CSharpName}.IsNull)" : $"\t\t\tif ({prop.CSharpName}.IsNull)");
					sb.AppendLine(model.GenerateAsNested ? $"\t\t\t\t\ttarget.{prop.CSharpName} = null;" : $"\t\t\t\ttarget.{prop.CSharpName} = null;");
					sb.AppendLine(model.GenerateAsNested ? "\t\t\t\telse" : "\t\t\telse");
					sb.AppendLine(model.GenerateAsNested ? $"\t\t\t\t\ttarget.{prop.CSharpName} = {prop.CSharpName}.Value;" : $"\t\t\t\ttarget.{prop.CSharpName} = {prop.CSharpName}.Value;");
				}
				else
					sb.AppendLine($"\t\t\t\ttarget.{prop.CSharpName} = {prop.CSharpName}.Value;");

				sb.AppendLine(model.GenerateAsNested ? "\t\t\t}" : "\t\t}");
			}
		}

		sb.AppendLine(model.GenerateAsNested ? "\t\t}" : "\t}");
		sb.AppendLine(model.GenerateAsNested ? "\t}" : "}");
		if (model.GenerateAsNested)
			sb.AppendLine("}");

		return sb.ToString();
	}

	private static string EscapeString(string value) =>
		value.Replace("\\", "\\\\").Replace("\"", "\\\"");

	private enum NestingMode
	{
		Automatic = 0,
		Subclass = 1,
		SameNamespace = 2
	}
}

internal static class StringExtensions
{
	public static string WithoutNullableSuffix(this string value) =>
		value.EndsWith("?") ? value.Substring(0, value.Length - 1) : value;
}