name: New JSON functionality
description: JSON can do something these libraries don't support
labels: ["feature"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to help make this project better!
  - type: textarea
    id: description
    attributes:
      label: Describe the functionality that isn't covered by this suite.
    validations:
      required: true
  - type: textarea
    id: alternatives
    attributes:
      label: Describe alternatives you've considered.
    validations:
      required: false
  - type: textarea
    id: other-info
    attributes:
      label: Is there any other information you'd like to share regarding this functionality?
    validations:
      required: false
  - type: input
    id: sponsor
    attributes:
      label: Are you representing an organization or employer?  If so, who?
    validations:
      required: false
  - type: checkboxes
    id: terms
    attributes:
      label: Code of Conduct
      description: By submitting this issue, you agree to follow our [Code of Conduct](https://github.com/json-everything/json-everything/blob/master/CODE_OF_CONDUCT.md)
      options:
        - label: I agree to follow this project's Code of Conduct
          required: true
