@JsonSchema.Test.Api_HostAddress = http://localhost:5042

POST {{JsonSchema.Test.Api_HostAddress}}/channel
Content-Type: application/json
Accept: application/json
{
  "na me": "jeff",
  "enabled": true
}

###
